### ISSUE TITLE
Jupyter notebook specifically detailing working with TS calculations.

### ISSUE THREAD

**Issue by logsdail** [logsdail/carmm#18]
We need a notebook to help people with TS calculations. @ikowalec this has been on your in-tray for some time - can I put you on this issue to resolve at some point? It doesn't need to be pretty, but we should get a first draft going.

**Comment by ikowalec** [comment]
I will give it a go during the weekend and will clean up next week.

**Comment by logsdail** [comment]
I've put a notebook in place for you!

**Comment by logsdail** [comment]
This has transferred over to external_examples, where the notebook needs finalising.

**Comment by logsdail** [comment]
@ikowalec can this be closed, or still working on aspects?
