### ISSUE TITLE
Update codebase to work with ASE v3.23

### ISSUE THREAD

**Issue by logsdail** [logsdail/carmm#30]
Issues include:
- socket calculator
- interpolation for NEB.

**Comment by ikowalec** [comment]
Vibrations (work in progress) @owainbeynon  - any tools should be written with the new `ase.vibrations.Vibrations` in mind

**Comment by logsdail** [comment]
I'm not sure how much backwards compatibility we need to maintain, this is going to be interesting to work out as the HPC versions of ASE are ~3.20

**Comment by logsdail** [comment]
Starting point is a branch with v3.23, and we see how much fails in the regression tests.
