### ISSUE TITLE
Accepting Multiple "Output" Options in React.py

### ISSUE THREAD

**Issue by GabrielBram** [logsdail/carmm#89]
As the 'output' key word is a dictionary key, it only maps to one value. However, this option can be invoked several times.. ASE has a separate optional argument for 'output' for the Aims calculator object, so implementing this option similarly would likely resolve this.

**Comment by ikowalec** [comment]
Sorry for the delay, would simply including `{"output": ["item1", "item2"]}` in `params` not suffice? The value in dictionary key-value pair can itself be a list.

**Comment by ikowalec** [comment]
@GabrielBram  Is this still an issue, given the response above?
